name: 'From GitHub Issue To MongoDB'
description: 'Use this action to convert issues into a unified JSON structure and save them in a MongoDB Collection.'
branding:
  icon: "check-square"
  color: green
env:
  MONGO_URI: MongoDB URI
  MONGO_DB: Database name to use
  MONGO_COLLECTION: Collection to use
inputs:
  template-path:
    description: 'Path to the issue form template file'
outputs:
  jsonString:
    description: 'JSON string'
runs:
  using: 'node16'
  main: 'dist/index.js'
