name: Build and Copy to v* branch
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Copy to v* branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - run: rm .gitignore
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .gitignore dist/
          git commit -m "build"
          git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:refs/heads/v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}